{{ if .Values.enable_aws_alb }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shieldrule-grpc-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.alb_cert_arn }}
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/group.name: shieldrule
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: 0-99
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  ingressClassName: alb
  rules:
    - host: grpc-{{ .Values.SHIELDRULE_ENVIRONMENT }}.sliderule.io
      http:
        paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: shieldrule-api-service
                  port:
                    number: 9520
    - host: grpc-{{ .Values.SHIELDRULE_ENVIRONMENT }}-eks.sliderule.io
      http:
        paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: shieldrule-api-service
                  port:
                    number: 9520
{{ end }}