apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldrule-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shieldrule-api
      role: shieldrule-api-role
  strategy: { }
  template:
    metadata:
      labels:
        app: shieldrule-api
        role: shieldrule-api-role
    spec:
      {{ if .Values.service_account_role }}
      serviceAccountName: tasks
      {{ end }}
      terminationGracePeriodSeconds: 300
      containers:
        - image: "{{ .Values.api_image_url }}:{{ .Values.SHIELDRULE_ENVIRONMENT }}"
          imagePullPolicy: Always
          name: shieldrule-api
          ports:
            - containerPort: 8000
            - containerPort: 9520
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            timeoutSeconds: 10
            initialDelaySeconds: 300
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            timeoutSeconds: 10
            initialDelaySeconds: 300
          resources:
            requests:
              memory: {{ .Values.api.resources.requests.memory }}
              cpu: {{ .Values.api.resources.requests.cpu }}
            limits:
              memory: {{ .Values.api.resources.limits.memory }}
              cpu: {{ .Values.api.resources.limits.cpu }}
          envFrom:
          - secretRef:
              name: api-secret
          volumeMounts:
            - mountPath: /tmp
              name: shieldrule-api-tmpfs
          securityContext:
            capabilities:
              drop:
                - all
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.POSTGRES_HOST| quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.POSTGRES_PORT | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.POSTGRES_DB | quote }}
            - name: AUDIENCE_URL
              value: {{ .Values.AUDIENCE_URL | quote }}
            - name: ISSUER_URL
              value: {{ .Values.ISSUER_URL | quote }}
            - name: AUTH0_ENVIRONMENT_PREFIX
              value: {{ .Values.AUTH0_ENVIRONMENT_PREFIX | quote }}
            - name: RESET_DB
              value: {{ .Values.RESET_DB | quote }}
            - name: USE_AUTH_0
              value: {{ .Values.USE_AUTH_0 | quote }}
            - name: ENVIRONMENT
              value: {{ .Values.ENVIRONMENT | quote }}
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.SENTRY_ENVIRONMENT | quote }}
            - name: METRICS_NAMESPACE
              value: {{ .Values.METRICS_NAMESPACE | quote }}
            - name: SLACK_REDIRECT_URI
              value: {{ .Values.SLACK_REDIRECT_URI | quote }}
            - name: SHIELDRULE_ENVIRONMENT
              value: {{ .Values.SHIELDRULE_ENVIRONMENT | quote }}
            - name: USE_INSTANCE_PROFILE
              value: {{ .Values.USE_INSTANCE_PROFILE | quote }}
            - name: SERVER_BUCKET
              value: {{ .Values.SERVER_BUCKET | quote }}
            - name: REDIS_HOST
              value: {{ .Values.REDIS_HOST | quote }}
            - name: REDIS_PORT
              value: {{ .Values.REDIS_PORT | quote }}
            - name: USE_REDIS
              value: {{ .Values.USE_REDIS | quote }}
            - name: USE_SQS
              value: {{ .Values.USE_SQS | quote }}
            - name: SQS_QUEUE_NAME
              value: {{ .Values.SQS_QUEUE_NAME | quote }}
            - name: SQS_URL
              value: {{ .Values.SQS_URL | quote }}
        - name: prometheus
          image: "{{ .Values.prometheus_image_url }}:{{ .Values.SHIELDRULE_ENVIRONMENT }}"
          ports:
            - containerPort: 12346
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
      restartPolicy: Always
      volumes:
        - emptyDir: {}
          name: shieldrule-api-tmpfs
status: {}
