apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shieldrule-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shieldrule-api
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50