apiVersion: v1
kind: Service
metadata:
  name: shieldrule-api-service
spec:
  type: NodePort
  selector:
    app: shieldrule-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: {{ .Values.ports.api }}
