apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldrule-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shieldrule-docs
      role: shieldrule-docs-role
  strategy: { }
  template:
    metadata:
      labels:
        app: shieldrule-docs
        role: shieldrule-docs-role
    spec:
      containers:
        - image: 600592424179.dkr.ecr.us-west-1.amazonaws.com/shieldrule-docs:dev
          name: shieldrule-docs
          ports:
            - containerPort: 8000
          resources: {}
          securityContext:
            capabilities:
              drop:
                - all
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: shieldrule-docs-tmpfs0
      restartPolicy: Always
      volumes:
        - emptyDir:
            medium: Memory
          name: shieldrule-docs-tmpfs0
status: {}
